In [36]:
import numpy as np

In [37]:
arr1 = np.random.randint(0,10,(4,4))
arr2 = np.random.randint(0,10,(4,4))

In [38]:
arr1

array([[6, 2, 5, 6],
       [5, 9, 2, 5],
       [2, 5, 0, 9],
       [5, 1, 3, 7]])

In [39]:
np.dot(arr1,arr2)

array([[ 52,  29, 113,  66],
       [ 45,  69,  82, 102],
       [ 30,  35,  69,  77],
       [ 39,  16,  95,  56]])

In [40]:
arr1.sum()

72

In [41]:
arr1.sum(axis=0)

array([18, 17, 10, 27])

In [42]:
arr1.sum(axis=1)

array([19, 21, 16, 16])

In [43]:
np.dot(arr1,arr2).max()

113

In [44]:
np.dot(arr1,arr2).min()

16

In [45]:
arr1

array([[6, 2, 5, 6],
       [5, 9, 2, 5],
       [2, 5, 0, 9],
       [5, 1, 3, 7]])

In [46]:
arr1.mean() #mean

4.5

In [47]:
arr1.std() #standard deviation

2.57390753524675

In [48]:
arr1.var() #variance

6.625

In [49]:
np.median(arr1)

5.0

In [50]:
np.mean(arr1)

4.5

In [51]:
arr1

array([[6, 2, 5, 6],
       [5, 9, 2, 5],
       [2, 5, 0, 9],
       [5, 1, 3, 7]])

In [52]:
arr1.max()

9

In [53]:
arr1.argmax()

5

In [54]:
arr1.transpose()

array([[6, 5, 2, 5],
       [2, 9, 5, 1],
       [5, 2, 0, 3],
       [6, 5, 9, 7]])

In [55]:
np.sin(arr1) # find sin theta

array([[-0.2794155 ,  0.90929743, -0.95892427, -0.2794155 ],
       [-0.95892427,  0.41211849,  0.90929743, -0.95892427],
       [ 0.90929743, -0.95892427,  0.        ,  0.41211849],
       [-0.95892427,  0.84147098,  0.14112001,  0.6569866 ]])

In [56]:
np.exp2(arr1) # 2^n where n is the member

array([[ 64.,   4.,  32.,  64.],
       [ 32., 512.,   4.,  32.],
       [  4.,  32.,   1., 512.],
       [ 32.,   2.,   8., 128.]])

In [57]:
np.power(3,arr1) # 3^n where n is the member

array([[  729,     9,   243,   729],
       [  243, 19683,     9,   243],
       [    9,   243,     1, 19683],
       [  243,     3,    27,  2187]], dtype=int32)

In [58]:
np.log(arr1)

C:\Users\TUSHAR BHUT\AppData\Local\Temp\ipykernel_15256\2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([[1.79175947, 0.69314718, 1.60943791, 1.79175947],
       [1.60943791, 2.19722458, 0.69314718, 1.60943791],
       [0.69314718, 1.60943791,       -inf, 2.19722458],
       [1.60943791, 0.        , 1.09861229, 1.94591015]])

In [59]:
arr1-arr1.mean() #moving data towards the mean

array([[ 1.5, -2.5,  0.5,  1.5],
       [ 0.5,  4.5, -2.5,  0.5],
       [-2.5,  0.5, -4.5,  4.5],
       [ 0.5, -3.5, -1.5,  2.5]])

In [65]:
print(arr1)
arr1[arr1>5]

[[6 2 5 6]
 [5 9 2 5]
 [2 5 0 9]
 [5 1 3 7]]


array([6, 6, 9, 9, 7])

In [75]:
a = np.array([2,3,5,4,6,8])
b = np.array([2,3,5,4,6,8,9])

In [76]:
a==b

C:\Users\TUSHAR BHUT\AppData\Local\Temp\ipykernel_15256\464372380.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a==b


False

In [79]:
arr1

array([[6, 2, 5, 6],
       [5, 9, 2, 5],
       [2, 5, 0, 9],
       [5, 1, 3, 7]])

In [83]:
np.count_nonzero(arr1>7) # count value that greater than 7

2

In [85]:
mylist = []
ip = input("Enter Numbers: ")
ip.split(",")
print(ip)